### ISSUE TITLE
Support for `deepObject` in query

### ISSUE THREAD

**Issue by lauritzsh** [drwpow/openapi-typescript#1042]
**Description**

OpenAPI has a `deepObject` option for query which is a way to nest query parameters such as `paramName[prop1]=value1&paramName[prop2]=value2&...`. The issue is right now that the schema will have ambiguous definition generated when mixing `deepObject` and nothing.

https://swagger.io/docs/specification/serialization/ (scroll down to "Query Parameters")

**OpenAPI**

```yaml
paths:
  "/example":
    get:
      summary: example
      description: example
      tags:
        - Example
      operationId: Example
      parameters:
        - name: pagination
          in: query
          schema:
            type: object
            properties:
              page:
                type: integer
                minimum: 1
              items:
                type: integer
                minimum: 1
        - name: sort
          in: query
          style: deepObject
          schema:
            type: object
            properties:
              last_status_updated_at:
                type: string
                enum:
                  - asc
                  - desc
        - name: filter
          in: query
          style: deepObject
          schema:
            type: object
            properties:
              trader:
                type: string
              action:
                type: string
                enum:
                  - buy
                  - sell
              status:
                type: string
                enum:
                  - completed
                  - failed
                  - pending
                  - created
```

**Generated TS**

```ts
    parameters: {
      query: {
        pagination?: {
          page?: number
          items?: number
        }
        sort?: {
          /** @enum {string} */
          last_status_updated_at?: 'asc' | 'desc'
        }
        filter?: {
          trader?: string
          /** @enum {string} */
          action?: 'buy' | 'sell'
          /** @enum {string} */
          status?: 'completed' | 'failed' | 'pending' | 'created'
        }
      }
    }
```

**Expected TS*

```ts
    parameters: {
      query: {
        page?: number
        items?: number
        sort?: {
          /** @enum {string} */
          last_status_updated_at?: 'asc' | 'desc'
        }
        filter?: {
          trader?: string
          /** @enum {string} */
          action?: 'buy' | 'sell'
          /** @enum {string} */
          status?: 'completed' | 'failed' | 'pending' | 'created'
        }
      }
    }
```

**Checklist**

- [x] My OpenAPI schema passes a validator
- [ ] I’m willing to open a PR for this (see [CONTRIBUTING.md](https://github.com/drwpow/openapi-typescript/blob/main/CONTRIBUTING.md))
