### ISSUE TITLE
Java MultiValueMap generates invalid types when run through openapi-typescript

### ISSUE THREAD

**Issue by djMax** [drwpow/openapi-typescript#1273]
**Description**

The following OpenAPI component:

```
    MultiValueMapStringString:
      type: object
      properties:
        all:
          type: object
          additionalProperties:
            type: string
          writeOnly: true
        empty:
          type: boolean
      additionalProperties:
        type: array
        items:
          type: string
```

Generates the following invalid Typescript:
```
    MultiValueMapStringString: {
      all?: {
        [key: string]: string | undefined;
      };
      empty?: boolean;
      [key: string]: string[] | undefined;
    };
```

```
Property 'all' of type '{ [key: string]: string; }' is not assignable to 'string' index type 'string[]'.ts(2411)
```

| Name                 | Version                      |
| :------------------- | :--------------------------- |
| `openapi-typescript` | `6.3.9`                      |
| Node.js              | `18.16.0`                      |
| OS + version         | `macOS 13.2.1` |

**Reproduction**

The schema above should generate the invalid Typescript

**Expected result**

**Checklist**

- [X] My OpenAPI schema passes the [Redocly validator](https://redocly.com/docs/cli/commands/lint/) (`npx @redocly/cli@latest lint`) - lots of little nits about summaries and such, but overall yes
- [X] I’m willing to open a PR (see [CONTRIBUTING.md](https://github.com/drwpow/openapi-typescript/blob/main/CONTRIBUTING.md))
