### ISSUE TITLE
OneOf type generating `Record<string,never>` despite all types defined

### ISSUE THREAD

**Issue by mattoni** [drwpow/openapi-typescript#1277]
**Description**

I have the following definition for an object:
```
title: StepResourceLocation
type: object
description: Either a details ID or details from where the ID is an identifier for an existing resource and a from is an identifier from a previous step in this pipeline.
oneOf:
  - title: DetailsId
    type: object
    required:
      - id
    properties:
      id:
        type: string
        description: The ID of an existing resource that exists before the pipeline is run.
  - title: DetailsFrom
    type: object
    required:
      - from
    properties:
      from:
        type: object
        description: The stage and step to report on.
        required:
          - step
        properties:
          stage:
            type: string
            description: An identifier for the stage the step being reported on resides in.
          step:
            type: string
            description: An identifier for the step to be reported on.
```
However, the generated type is: 
```
    /**
     * StepResourceLocation
     * @description Either a details ID or details from where the ID is an identifier for an existing resource and a from is an identifier from a previous step in this pipeline.
     */
    ResourceLocation: Record<string, never> & OneOf<[{
      /** @description The ID of an existing resource that exists before the pipeline is run. */
      id: string;
    }, {
      /** @description The stage and step to report on. */
      from: {
        /** @description An identifier for the stage the step being reported on resides in. */
        stage?: string;
        /** @description An identifier for the step to be reported on. */
        step: string;
      };
    }]>;
```

I cannot figure out why it's generating `Record<string, never>` here. This is a pretty straightforward `oneOf`, and the options are being generated correctly otherwise.

| Name                 | Version                      |
| :------------------- | :--------------------------- |
| `openapi-typescript` | `6.4.0`                      |
| Node.js              | `19.0.0`                      |
| OS + version         | `Linux Pop!_OS 22.04 LTS` |

**Reproduction**

Run the above through openapi-typescript generator

**Expected result**

There should be no `Record<string,never>` as part of this definition.
**Checklist**

- [x] My OpenAPI schema passes the [Redocly validator](https://redocly.com/docs/cli/commands/lint/) (`npx @redocly/cli@latest lint`)
- [ ] I’m willing to open a PR (see [CONTRIBUTING.md](https://github.com/drwpow/openapi-typescript/blob/main/CONTRIBUTING.md))
