### ISSUE TITLE
Error types cannot be used (expression of type '"..."' can't be used to index type 'NonNullable<FilterKeys<...>>)

### ISSUE THREAD

**Issue by EmilePerron** [drwpow/openapi-typescript#1291]
**Description**

When making an API call using the library, using fairly simple code like below, the error object does not allow access to any of the keys that are supposed to be available.

Ex.:

```ts
const client = createClient<paths>({ baseUrl: apiBaseUrl, headers: { ...baseHeaders, Authorization: `Bearer ${jwt}` } });
const response = await client.post("/rtm/notes/create", { body: data });

if (response.error) {
  enqueueSnackbar({
    message: response.error["hydra:description"],
    variant: "error",
    autoHideDuration: 10000,
  });

  return;
}
```

Gives the following error when using `response.error["hydra:description"]` (or any other key/property on the error):

```
Element implicitly has an 'any' type because expression of type '"hydra:description"' can't be used to index type 'NonNullable<FilterKeys<{ "application/ld+json": { "@context": string; "@type": string; "hydra:title": string; "hydra:description": string; }; "application/json": { code?: string | undefined; message?: string | undefined; }; } | { ...; } | { ...; }, `${string}/${string}`>>'.
  Property 'hydra:description' does not exist on type 'NonNullable<FilterKeys<{ "application/ld+json": { "@context": string; "@type": string; "hydra:title": string; "hydra:description": string; }; "application/json": { code?: string | undefined; message?: string | undefined; }; } | { ...; } | { ...; }, `${string}/${string}`>>'.ts(7053)
```

Here is the Typescript error in VS Code:

<img width="963" alt="image" src="https://github.com/drwpow/openapi-typescript/assets/9383532/c6b50f75-c9e1-4362-b1d4-cec7ed96a8ed">

My OpenAPI schema for the responses is the following:
```yaml
400:
  description: 'Invalid input'
  content:
    application/ld+json:
      schema:
        type: object
        properties:
          '@context': { readOnly: true, type: string, nullable: false }
          '@type': { readOnly: true, type: string, nullable: false }
          'hydra:title': { readOnly: true, type: string, nullable: false }
          'hydra:description': { readOnly: true, type: string, nullable: false }
        required:
          - '@context'
          - '@type'
          - 'hydra:title'
          - 'hydra:description'
    application/json:
      schema:
        type: object
        properties:
          code: { readOnly: true, type: string, nullable: false }
          message: { readOnly: true, type: string, nullable: false }
        required:
          - '@context'
          - '@type'
          - 'hydra:title'
          - 'hydra:description'
422:
  description: 'Unprocessable entity'
  content:
    application/ld+json:
      schema:
        type: object
        properties:
          '@context': { readOnly: true, type: string, nullable: false }
          '@type': { readOnly: true, type: string, nullable: false }
          'hydra:title': { readOnly: true, type: string, nullable: false }
          'hydra:description': { readOnly: true, type: string, nullable: false }
          violations: { readOnly: true, type: array, items: { type: object, properties: { code: { type: string, readOnly: true, nullable: false }, message: { type: string, readOnly: true, nullable: false }, propertyPath: { type: string, readOnly: true, nullable: false } } } }
        required:
          - '@context'
          - '@type'
          - 'hydra:title'
          - 'hydra:description'
    application/json:
      schema:
        type: object
        properties:
          code: { readOnly: true, type: string, nullable: false }
          message: { readOnly: true, type: string, nullable: false }
          violations: { readOnly: true, type: array, items: { type: object, properties: { code: { type: string, readOnly: true, nullable: false }, message: { type: string, readOnly: true, nullable: false }, propertyPath: { type: string, readOnly: true, nullable: false } } } }
        required:
          - '@context'
          - '@type'
          - 'hydra:title'
          - 'hydra:description'
```

Perhaps it's related to #1128, but my understanding of it is that it would default the `error`'s type to the `400`'s format - not cause the error above. Do let me know if I'm wrong about this!

**Reproduction**

This is a typescript error, and so I expect reproducing the code above using the provided API responses schema would trigger the same error.

**Expected result**

Until #1128 is resolved, my expected result would've been that `error` be typed as the schema/type for `400`, and that its properties could be accessed without any errors.

**Checklist**

- [x] I’m willing to open a PR (see [CONTRIBUTING.md](https://github.com/drwpow/openapi-fetch/blob/main/CONTRIBUTING.md))

(I don't expect that'll be necessary as I feel I might just be doing something wrong, but if it's something I can fix in a PR, I'd be happy to!)

Thanks in advance! :)
