### ISSUE TITLE
Array of Enum generate wrong union type (no quotes)

### ISSUE THREAD

**Issue by muyaszed** [drwpow/openapi-typescript#1292]
**Description**

When having a yaml specifying a parameter with an enum of an array type, the generated type having the wrong format of union type

**Reproduction**
yaml file
```
newParam:
      name: newParam
      in: query
      required: false
      schema:
        type: array
        enum:
          - firstEnum
          - secondEnum
```

**Expected result**

generated file
```
parameters: {
    newParam: firstEnum | secondEnum;
};
```
the quotes is missing making the enums to be undefined

Is this something as expected or maybe it is a bug?

**Comment by drwpow** [comment]
I don’t believe that’s correct syntax. An array can’t directly have an `enum` like that; you should either be setting the `enum` on the `items` subtype like so:

```yaml
newParam:
  name: newParam
  in: query
  required: false
  schema:
    type: array
    items:
      type: string
        enum:
          - firstEnum
          - secondEnum
```

Or if you want to generate a tuple type, you can use [prefixItems](https://json-schema.org/understanding-json-schema/reference/array.html#id7) or [minItems / maxItems](https://json-schema.org/understanding-json-schema/reference/array.html#id12).

Remember that openapi-typescript will **NOT** validate your schema for you, and will not alert you of errors. We highly recommend the [Redocly CLI](https://redocly.com/docs/cli/commands/lint/#lint) for that.
