### ISSUE TITLE
Explode keyword is ignored

### ISSUE THREAD

**Issue by FrauElster** [drwpow/openapi-typescript#1388]
**Description**

The `explode` keyword for URL query params is ignored. Spec is [here](https://swagger.io/specification/?sbsearch=explode)
**Reproduction**

_How can this be reproduced / when did the error occur? Does the issue occur in a specific browser, or all browsers?_

```
paths:
  /:
    parameters:
      - in: query
        name: bookId
        explode: true
        description: the id of the book
        schema:
          type: array
          items:
            type: string
```

**Expected result**

Instead of `http://www.example.com/books?id=1,2,3,` it should be `http://www.example.com/books?id=1&id=2&id=3` if `explode: true`

**Checklist**

- [ ] I’m willing to open a PR (see [CONTRIBUTING.md](https://github.com/drwpow/openapi-fetch/blob/main/CONTRIBUTING.md))
