### ISSUE TITLE
Nullable fields not respected in intercom schema?

### ISSUE THREAD

**Issue by cipriancaba** [drwpow/openapi-typescript#1422]
**Description**

This is my first time using this library, it's absolutely amazing, thank you so much 🙏

I'm having a bit of trouble with the `| undefined` parts of the generated types. It seems that absolutely everything is `| undefined` For example, in this call to GET `/tags`, it correctly discriminates the non error nature of the response, but the generated type is:

```
tags.data.data is possibly 
 .
(property) data?: {
    [key: string]: unknown;
    type?: string | undefined;
    id?: string | undefined;
    name?: string | undefined;
    applied_at?: number | undefined;
    applied_by?: {
        ...;
    } | undefined;
}[] | undefined
```

And here is my code
```
const tags = await intercomClient.GET('/tags')
  if (tags.error) {
    return NextResponse.json(tags.error)
  }

  for (const tag of tags.data.data) { //<-- errors here as data array can be undefined
    console.log(tag)
  }
```

Been playing around with the --default-non-nullable but it doesn't seem to do the trick. I'm sure it's an obvious problem, but I can't figure it out. 

Thanks for the help

| Name                 | Version                      |
| :------------------- | :--------------------------- |
| `openapi-typescript` | `7.0.0-next.2`                      |
| Node.js              | `18.20`                      |
| OS + version         | `macOS Sonoma` |

**Reproduction**

https://gist.github.com/cipriancaba/790b7366794640779f0ca662f759ef8e

`npx openapi-typescript@next intercom.yaml -o intercom.d.ts`

**Expected result**

Generated data type shouldn't be `| undefined`, unless nullable is specified in the yaml schema eg:

```
(property) data?: {
    [key: string]: unknown;
    type?: string;
    id?: string;
    name?: string;
    applied_at?: number;
    applied_by?: {
        ...;
    };
}[]
```

**Checklist**

- [x] My OpenAPI schema passes the [Redocly validator](https://redocly.com/docs/cli/commands/lint/) (`npx @redocly/cli@latest lint`)
- [ ] I’m willing to open a PR (see [CONTRIBUTING.md](https://github.com/drwpow/openapi-typescript/blob/main/packages/openapi-typescript/CONTRIBUTING.md))

**Comment by drwpow** [comment]
Taking a quick glance at your schema, I think it’s because you have `nullable: true` set on many schema objects, as well as missing a lot of `required` arrays. At first glance it seems to be generating the types as-expected, but if there’s a specific example that seems weird I’d be happy to take a closer look.

**Comment by drwpow** [comment]
Also `--default-non-nullable` is for something different. That’s for times when you are setting a `default` key to treat it as if the property is `required` even if it’s not explicitly set. In v7 and beyond this defaults to `true`; the only reason it exists still is for backwards compatibility with the previous behavior (e.g. `--default-non-nullable=false`)

**Comment by cipriancaba** [comment]
Hey, thanks so much for being so helpful. I've created a repo showing my problem here https://github.com/cipriancaba/openapi-typescript

![Screenshot 2023-11-03 at 15 50 25](https://github.com/drwpow/openapi-typescript/assets/695515/29e81a2b-c995-404e-af59-ded13ae83627)

This is the schema for the specific `GET /tags` request

```

tag:
      title: Tag
      type: object
      x-tags:
      - Tags
      description: A tag allows you to label your contacts, companies, and conversations
        and list them using that tag.
      properties:
        type:
          type: string
          description: value is "tag"
          example: tag
        id:
          type: string
          description: The id of the tag
          example: '123456'
        name:
          type: string
          description: The name of the tag
          example: Test tag
        applied_at:
          type: integer
          format: date-time
          description: The time when the tag was applied to the object
          example: 1663597223
        applied_by:
          "$ref": "#/components/schemas/reference"
```

I can see indeed it is missing the required property as `true`. Is the default expectation that a missing require is actually false? If so, is there a way to toggle that and maybe just consider a field nullable if nullable is set to `true` in the schema?
