### ISSUE TITLE
Add new custom property that is not exposed in OpenAPI schemas

### ISSUE THREAD

**Issue by brojd** [drwpow/openapi-typescript#1450]
**Description**

I'm currently checking possibility of using the library in my team. The situation we have is that we have some issues annotating each and every property on the backend which in turn results in missing properties in OpenAPI schemas. 

At the same time I want to gradually migrate frontend codebase to use the types generated by openapi-typescript and 
openapi-fetch http client that use autogenerated types.

I'm looking for a solution to add custom properties in components that are missing in OpenAPI schemas. For example in autogenerated types I have:
```
export interface components {
  schemas: {
    Alert: {
      id: string;
    }
  }
}
```

`id` property is present in OpenAPI schema. But we also have `page` property that is returned by the backend but right now it is not exposed in OpenAPI schema. I'm looking for a way to configure openapi-typescript  so that it generates the following type:
```
export interface components {
  schemas: {
    Alert: {
      id: string;
      page: number;
    }
  }
}
```

How to achieve it?

**Comment by drwpow** [comment]
Modifying schemas isn’t something openapi-typescript can help with; this only converts your schema ro TypeScript. The best solution is to fix the original OpenAPI schema to match what the endpoint is returning.

As a workaround, you can use something like [Redocly CLI + a custom plugin](https://redocly.com/docs/cli/custom-plugins/) to programmatically modify a schema. But do this with caution, because you’re forking the source of truth! And this will lead to other issues that could be solved by just fixing the root schema.

**Comment by drwpow** [comment]
Going to close this issue as this isn’t something this library will ever support or encourage. But feel free to post followup questions or points of clarification.

**Comment by drwpow** [comment]
Note: also, to add on to my original suggestion, OpenAPI supports composition, so if, say, many objects are missing a `page` key, you could use [allOf](https://swagger.io/docs/specification/data-models/oneof-anyof-allof-not/) to easily extend it:

```yaml
components:
  schemas:
    Alert:
      type: object
      allOf:
        - "#/components/schemas/Pagination"
      required: ["id"]
      properties:
        id:
          type: string
    Pagination:
      type: object
      required: ["page"]
      properties:
        page:
          type: number
```

This lets you dedupe code and reduce errors in your schema, and is fairly quick to add (especially if you have hundreds of schema objects to modify)
