### ISSUE TITLE
Adding 'openapi-ts' property in .redocly.yaml results in Redocly lint warning

### ISSUE THREAD

**Issue by akindo** [drwpow/openapi-typescript#1463]
**Description**

Adding 'openapi-ts' property in `.redocly.yaml` results in Redocly lint warning.

```
Property `openapi-ts` is not expected here.
```

| Name                 | Version                      |
| :------------------- | :--------------------------- |
| `openapi-typescript` | `7.0.0-next.4`                      |
| Node.js              | `v18.18.2`                      |
| OS + version         | `macOS 14.1.1` |

**Reproduction**

Add to `.redocly.yaml`:

```
apis:
  hello-world-api:
    root: openapi/openapi.yaml
    openapi-ts:
      output: src/types/openapi.ts
```

**Expected result**

No lint warning.

**Checklist**

- [] My OpenAPI schema passes the [Redocly validator](https://redocly.com/docs/cli/commands/lint/) (`npx @redocly/cli@latest lint`)
- [] I’m willing to open a PR (see [CONTRIBUTING.md](https://github.com/drwpow/openapi-typescript/blob/main/packages/openapi-typescript/CONTRIBUTING.md))
