### ISSUE TITLE
openapi-typescript cmd idle when using redocly.yaml

### ISSUE THREAD

**Issue by ootkin** [drwpow/openapi-typescript#1515]
**Description**

If you have `redocly.yaml` in the root of the project, the `npx openapi-typescript` command does not generate output and it stay idle.

| Name                 | Version                      |
| :------------------- | :--------------------------- |
| `openapi-typescript` | `6.7.4`                      |
| Node.js              | `v20.10.0`                      |
| OS + version         | `macOS 14.0` |

**Reproduction**

Create a `redocly.yaml`in the root of the project like this:
```yaml
resolve:
  http:
    headers:
      - matches: https://subdomain.readme.io/openapi/*
        name: Authorization
        value: "Basic TOKEN"
apis:
  accounting:
    root: https://subdomain.readme.io/openapi/...
    x-openapi-ts:
      output: ./openapi/openapi.ts
  content:
    root: https://subdomain.readme.io/openapi/...
    x-openapi-ts:
      output: ./openapi/openapi.ts
```
Run `npx openapi-typescript` with no options.

Nothing happens, the process does not exit.
