### ISSUE TITLE
Query serializer ignores explicit "explode" field value

### ISSUE THREAD

**Issue by jens1101** [drwpow/openapi-typescript#1608]
**Description**

The default query serializer ignores an explicit `explode` field value in the OpenAPI definition for that query parameter. Instead it will always use the global setting of the query serializer. This causes problems for OpenAPI specs which do not use a consistent vale for the `explode` field.

**Reproduction**

- Environment: Node v20
- Given the following OpenAPI snippet for a query parameter:
  ```yml
  parameters:
    - name: instruments
      in: query
      style: form
      explode: false
      schema:
        type: array
        items:
          type: string
  ```
- Given the following value for the `instruments` parameter:
  ```js
  ["USD_JPY", "EUR_USD", "EUR_JPY"]
  ```

The following query string is generated by default: `?instruments=USD_JPY&instruments=EUR_USD&instruments=EUR_JPY`.

**Expected result**

In this case the query string should have been `?instruments=USD_JPY,EUR_USD,EUR_JPY`.

**Checklist**

- [ ] I’m willing to open a PR (see [CONTRIBUTING.md](https://github.com/drwpow/openapi-typescript/blob/main/packages/openapi-fetch/CONTRIBUTING.md))
