### ISSUE TITLE
3.0 Support: “not?”

### ISSUE THREAD

**Issue by drwpow** [drwpow/openapi-typescript#203]
So the one 3.0 feature I’m thinking about not supporting is [not](https://swagger.io/docs/specification/data-models/oneof-anyof-allof-not/#not). The reason is… I’m not sure how!

According to the definition:

> The `not` keyword does not exactly combine schemas, but as all of the keywords mentioned above it helps you to modify your schemas and make them more specific.

The example given is:

```yaml
    PetByType:
      type: object
      properties:
        pet_type:
          not:
            type: integer
```

While that can be done in JavaScript at runtime (`typeof PetByType !== 'number'`), I don’t think it’s possible in TypeScript to create a type that’s equal to **anything but the given type.**

Am I wrong? Is this possible?
