### ISSUE TITLE
Support `$ref`-type parameters, as well as components.parameters

### ISSUE THREAD

**Issue by drwpow** [drwpow/openapi-typescript#329]
Followup from #236.

We don’t yet support the following schema:

```yaml
paths:
  '/some/path':
    get:
      parameters:
        - "$ref": "#/components/parameters/since"
        - "$ref": "#/components/parameters/per_page"
        - "$ref": "#/components/parameters/page"
```

Add support for `$ref` parameters as well as add the `components.parameters` object to the final response.

There’s an existing spec which illustrates this: `tests/v3/specs/github.yaml`.
