### ISSUE TITLE
anyOf clauses are combined via intersection (&), should be union (|)

### ISSUE THREAD

**Issue by dbjorge** [drwpow/openapi-typescript#462]
#### Summary

The transformation rules for an object schema with an `anyOf` clause look like this:
https://github.com/drwpow/openapi-typescript/blob/8a999ebaea31140b24632f6439dc3d4a41caa319/src/transform/schema.ts#L39-L41

This should be using a union, not an intersection.

#### Impact

This comes up in the GitHub OpenAPI specification (see https://github.com/octokit/rest.js/issues/2000 for one example in the check/update operation).

#### Explanation/repro

[This StackOverflow answer](https://stackoverflow.com/a/52838995) is a pretty thorough writeup of why a union would be more appropriate.

As an example where the current behavior is problematic, consider this case:

```yaml
# repro-schema.yaml
{
  "openapi": "3.0.3",
  "components": {
    "schemas": {
      "example": {
        "type": "object",
        "anyOf": [
          {
            "properties": {
              "anyof_prop_common": { "enum": [ "a" ] },
              "anyof_prop_a": { "type": "string" },
            },
            "required": [ "anyof_prop_common" ]
          },
          {
            "properties": {
              "anyof_prop_common": { "enum": [ "b" ] },
              "anyof_prop_b": { "type": "string" },
            },
            "required": [ "anyof_prop_common" ]
          },
        ],
      },
    },
  },
}
```

```ts
// test.ts
import { components } from './repro-typings';

type Example = components['schemas']['example'];
let exampleValue: Example;

exampleValue = {
    // This should be accepted, but this line actually fails to compile because the type of
    // components['schemas']['example']['anyof_prop_common'] is essentially "a" & "b", ie, "never"
    anyof_prop_common: 'a',
    anyof_prop_a: 'value'
};
```

```bash
> npx openapi-typescript .\repro-schema.yaml -o .\repro-typings.ts
✨ openapi-typescript 3.0.0
🤞 Loading spec from .\repro-schema.yaml…
🚀 .\repro-schema.yaml -> .\repro-typings.ts [197ms]

> npx tsc .\test.ts
test.ts:10:5 - error TS2322: Type 'string' is not assignable to type 'never'.

10     anyof_prop_common: 'a',
       ~~~~~~~~~~~~~~~~~

  repro-typings.ts:11:7
    11       anyof_prop_common: "a";
             ~~~~~~~~~~~~~~~~~
    The expected type comes from property 'anyof_prop_common' which is declared here on type 'Partial<{ anyof_prop_common: "a"; anyof_prop_a?: string; }> & Partial<{ anyof_prop_common: "b"; anyof_prop_b?: string; }>'


Found 1 error.
```

#### Related cases

Separately from this bug, [the same SO post I linked above](https://stackoverflow.com/a/52838995) has a good discussion of how to handle `oneOf`, which is much harder to convert in a way that is accurate. Personally, I think it is more valuable for this library to produce typings that are over-accepting than under-accepting, so based on the tradeoffs that SO post talks about, I would recommend keeping the current oneOf behavior (ie, oneOf and anyOf will produce identical typings) and consider it acceptable that this will cause the library to be over-accepting of cases where a `oneOf` schema should reject input that `anyOf` would accept.

This bug was discovered at the same time/for the same motivating case as #461, but is a separate root cause.
