### ISSUE TITLE
Wrong generated type when processing enums containing "null"

### ISSUE THREAD

**Issue by FedeBev** [drwpow/openapi-typescript#482]
Hi there,

with swagger 2 definition like the following
```yaml
field:
    type: string
    enum: ["N", "L", null]
    nullable: true
 ```
 
 the following code is generated
 ```
 "field"?: (('N') | ('L') | ()) | null;
 ```
 
 resulting in a syntax error: `SyntaxError: '=>' expected.`
 
 This could be related to #447 and #234 
 
 openapi-typescript version: 3.0.1
