### ISSUE TITLE
Feature request: optional flag to type a field as Date for date-time or date formats

### ISSUE THREAD

**Issue by josh-feldman** [drwpow/openapi-typescript#544]
I am working on a project using OpenAPI v3 and the schema contains objects which use the type string with the format `date-time`.

example:

```yaml
SomethingWithATimestamp:
  title: SomethingWithATimestamp
  type: object
  properties:
    timestamp:
      type: string
      format: date-time
      example: "2021-03-29T17:18:30.966Z"
```

The Typescript output generated by `openapi-typescript` results in  type `string` (as intended). But in our case having it parsed as `Date` would save us a lot of manual unwrapping and `.toISOString()` calls, as `JSON.stringify` will convert the dates to ISO strings for us after calling `res.send()`.

Therefore, an optional flag to enable parsing strings with the `date-time` or `date` format as `Date` would be very helpful!
