### ISSUE TITLE
Support for `const` definitions

### ISSUE THREAD

**Issue by tshelburne** [drwpow/openapi-typescript#685]
Currently we have to use the following schema to define constants:

```yml
value:
  type: string
  enum: [some-constant]
```

Which results in:

```ts
type value = 'some-constant'
```

JSON schema supports defining with the `const` property, and it looks like [OAI](https://github.com/OAI/OpenAPI-Specification/issues/1313#issuecomment-572766938) has adopted it as well? The definition would look like this:

```yml
value:
  type: string
  const: some-constant
```

And would result in the same Typescript as above.
