### ISSUE TITLE
Schema without a type should be "any" or "unknown" instead of a generic map type

### ISSUE THREAD

**Issue by pbzdyl** [drwpow/openapi-typescript#693]
According to the [OpenAPI spec](https://swagger.io/docs/specification/data-models/data-types/#any), when a schema is defined without a type it is the equivalent of:

```
      anyOf:
        - type: string
        - type: number
        - type: integer
        - type: boolean
        - type: array
          items: {}
        - type: object
```

but openapi-typescript uses [`object` type as the default](https://github.com/drwpow/openapi-typescript/blob/main/src/types.ts#L102) and [generates](https://github.com/drwpow/openapi-typescript/blob/main/src/transform/schema.ts#L116-L121) `{ [key: string]: unknown }`. Instead it should generate just `unknown`.
