### ISSUE TITLE
Feature request: support for external files in $ref

### ISSUE THREAD

**Issue by berzi** [drwpow/openapi-typescript#892]
[The OpenAPI specification](https://swagger.io/specification/#document-structure) explicitly declares support for splitting specification files into multiple files, referencing the pieces through `$ref`.

As far as I know, this is not supported by openapi-typescript, and as a result any user of this utility must forgo the ability to split up their API spec file, which for larger applications can result in files spanning multiple thousands of lines.

I think this feature would be a very important addition, not to mention that ideally, the utility should support everything that the OpenAPI specification allows to avoid forcing users out of desirable features.

**Comment by drwpow** [comment]
This does support remote `$ref`s! There’s [even a test for it here](https://github.com/drwpow/openapi-typescript/blob/main/test/opts/remote-schema.test.js#L7).

But perhaps there’s some feature of remote `$ref`s missing? Would love for someone to add more tests to this, and fix any missing parts of the OpenAPI schema this library currently doesn’t support 🙏

**Comment by berzi** [comment]
Are *local* $refs also supported?

**Comment by drwpow** [comment]
In-document `$ref`s are supported, `$ref`s in other files on the local filesystem are supported, and `$ref`s to reachable URLs are supported (this library also has basic auth support if needed). If there is a bug in any of those items, a bug reproduction would be much appreciated 🙏

**Comment by berzi** [comment]
My colleagues mentioned that much-desired feature didn't work for them. I'll test it out myself soon and report back. :)

**Comment by joshunger** [comment]
@drwpow can you please give me a tip on what needs to be fixed here?

root.yaml
```
      responses:
        '200':
          content:
            application/json:
              schema: { $ref: 'coupon_response.yaml#/CouponResponse' }
```

coupon_response.yaml
```
CouponResponse:
  type: array
  items: { $ref: 'coupon.yaml#/Coupon' }
```

Skipping Coupon for now.

Generated:
```
export interface external {
  'coupon_response.yaml': {
    paths: {};
    components: {};
    operations: {};
  };
```

**Comment by berzi** [comment]
@joshunger Have you tried using paths like `./coupon.yaml` and `./coupon_response.yaml`?

**Comment by joshunger** [comment]
@berzi still empty can you share a snippet you're using? Thanks.

**Comment by berzi** [comment]
> @berzi still empty can you share a snippet you're using? Thanks.

```yaml
# openapi.yaml

# ...

paths:
  /users/{userId}:
    parameters:
      - $ref: './users.yaml#/components/parameters/UserParameter'
    get:
      description: |
        Information about the currently logged in user.
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: './users.yaml#/components/schemas/User'
```

```yaml
# users.yaml

# ...

components:
  parameters:
    UserParameter:
      name: userId
      in: path
      schema:
        type: string
      required: true

  schemas:
    User:
      type: object
      required:
          - id
      properties:
        id:
          type: number
        name:
          type: string
```

**Comment by joshunger** [comment]
@berzi thanks, putting it under `components/schemas` fixed the issue for me. Appreciate it!

**Comment by ctjhoa** [comment]
In my case, `paths` contains `$ref` which are pointing to other files on the local filesystem and it doesn't work 
 
Like 
```yaml
    paths:
      /users:
        $ref: '../resources/users.yaml'
      /users/{userId}:
        $ref: '../resources/users-by-id.yaml'
```

src: https://swagger.io/docs/specification/using-ref/#allowed-places

It fails to generate valid typescript code
```
SyntaxError: Type expected. (8:13)
   6 |
   7 | export interface paths {
>  8 |   "/users": ../resources/users.yaml;
     |             ^
   9 |   "/users/{userId}": ../resources/users-by-id.yaml;
  10 | }

```
