### ISSUE TITLE
Support nullable as type arrays for OpenAPI 3.1

### ISSUE THREAD

**Issue by timomeh** [drwpow/openapi-typescript#898]
In OpenAPI v3.1 `nullable: true` was removed in favor of type arrays with the value `"null"`. Reference: https://www.openapis.org/blog/2021/02/16/migrating-from-openapi-3-0-to-3-1-0

```yaml
# OpenAPI v3.0
type: string
nullable: true

# OpenAPI v3.1
type:
- "string"
- "null" 
```

The current version of openapi-typescript generates those properties as `unknown`, instead of `string | null`.
