### ISSUE TITLE
Not possible to create "any" schema

### ISSUE THREAD

**Issue by henhal** [drwpow/openapi-typescript#899]
According to [the spec](https://swagger.io/docs/specification/data-models/data-types/#any), an empty schema represents _any type_. However, any schema without `type` renders a `{[key: string]: any}` type.

Schema:
```
AnyValue: { }
```

Generated type:
```
...
AnyValue: { [key: string]: any }  
...
```

This means that it doesn't seem possible to create a schema which is e.g. a string, number or object, using this technique.

A side-effect is also that when using `allOf` to combine a schema without `type`, it implicitly adds a `& { [key: string]: any}`.

```
MyCombinedSchema:
  allOf:
    - description: Foo bar
    - $ref: '#/components/schemas/MyType'
```

=>

`MyCombinedSchema: { [key: string]: any } & string;`

This makes "inheritance" quite hard, since you have to explicitly add a `type` to every simple description schema etc.

Expected behaviour:

1. When a sub-schema within a combined schema (`allOf` etc) has no `type`, ignore it completely

```
# render TS type "string | number"
MyCombinedSchema:
  allOf:
    - type: string
    - type: number
    - description: Foo! # Ignore this sub-schema's undefined type, i.e., do NOT render string | number | any
```

2. When a resolved schema (simple schema or combined from sub-schemas using `allOf` etc) schema has no `type`, use `any` as the TypeScript type.

```
# render TS type "any"
MySimpleSchema:
  description: Foo! 

# render TS type "any" - see https://swagger.io/docs/specification/data-models/data-types/#any
MyAnyType: {}

# render TS Type "any"
MyCombinedSchema:
  allOf:
    - description: Foo!
    - description: Bar! 
```
